# Let's take on this challenge of new beinnings!

## Importing the Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cluster import KMeans
from sklearn import metrics
import pickle


## Now we add the dataset

In [2]:
path = "DataEdited.csv"

In [3]:
dataset = pd.read_csv(path)
dataset.head()

Test_age_T1  Body_height_cm_T1  Sitting_height_cm_T1  Arm_span_cm_T1  \
0          172              181.8                  91.8           184.0   
1          172              170.7                  91.3           169.8   
2          178              183.0                  94.1           181.4   
3          178              184.2                  93.0           188.8   
4          184              184.7                  96.6           183.5   

   Arm_length_cm_T1  Leg_length_cm_T1  Chest_girth_cm_T1  \
0              78.4              97.3               79.2   
1              70.2              88.2               81.1   
2              76.8              95.8               80.0   
3              82.4              99.6               78.3   
4              78.7              97.0               91.8   

   Shoulder_width_cm_T1  Crista_width_cm_T1  Calf_girth_cm_T1  ...  \
0                  36.2                27.7              33.0  ...   
1                  37.1                28.3              35.5  ...   
2                  39.4                28.2              34.8  ...   
3                  36.4                27.9              33.1  ...   
4                  37.7                26.8              34.6  ...   

   Ankle_circumference_cm_T1  Subscapular_angle_mm_T1  Abdomen_mm_T1  \
0                       20.8                      5.0            9.5   
1                       21.7                      7.5            9.0   
2                       21.6                      6.0            7.0   
3                       24.2                      6.0            7.5   
4                       21.0                      5.5            8.0   

   Upper_arm_mm_T1  Tendon_length_cm_T1  Body_weight_kg_T1  \
0             10.0                 28.8               57.1   
1              8.5                 23.0               56.3   
2              8.5                 24.2               58.9   
3              9.0                 26.1               57.0   
4             10.0                 24.9               63.1   

   Eye_hand_reaction_time  Heart_rate_rest_bpm_T1  Vital_capacity_ml_T1  \
0                     202                      69                  4315   
1                     234                      62                  3555   
2                     233                      76                  4450   
3                     201                      75                  4045   
4                     190                      60                  4145   

        Sport  
0  basketball  
1  basketball  
2  basketball  
3  basketball  
4  basketball  

[5 rows x 23 columns]

## Data Preprocessing

In [4]:
from sklearn.preprocessing import LabelEncoder
from sklearn import utils
le = LabelEncoder()
dataset["Sport"] = le.fit_transform(dataset["Sport"])
dataset.dtypes
dataset.head()

Test_age_T1  Body_height_cm_T1  Sitting_height_cm_T1  Arm_span_cm_T1  \
0          172              181.8                  91.8           184.0   
1          172              170.7                  91.3           169.8   
2          178              183.0                  94.1           181.4   
3          178              184.2                  93.0           188.8   
4          184              184.7                  96.6           183.5   

   Arm_length_cm_T1  Leg_length_cm_T1  Chest_girth_cm_T1  \
0              78.4              97.3               79.2   
1              70.2              88.2               81.1   
2              76.8              95.8               80.0   
3              82.4              99.6               78.3   
4              78.7              97.0               91.8   

   Shoulder_width_cm_T1  Crista_width_cm_T1  Calf_girth_cm_T1  ...  \
0                  36.2                27.7              33.0  ...   
1                  37.1                28.3              35.5  ...   
2                  39.4                28.2              34.8  ...   
3                  36.4                27.9              33.1  ...   
4                  37.7                26.8              34.6  ...   

   Ankle_circumference_cm_T1  Subscapular_angle_mm_T1  Abdomen_mm_T1  \
0                       20.8                      5.0            9.5   
1                       21.7                      7.5            9.0   
2                       21.6                      6.0            7.0   
3                       24.2                      6.0            7.5   
4                       21.0                      5.5            8.0   

   Upper_arm_mm_T1  Tendon_length_cm_T1  Body_weight_kg_T1  \
0             10.0                 28.8               57.1   
1              8.5                 23.0               56.3   
2              8.5                 24.2               58.9   
3              9.0                 26.1               57.0   
4             10.0                 24.9               63.1   

   Eye_hand_reaction_time  Heart_rate_rest_bpm_T1  Vital_capacity_ml_T1  Sport  
0                     202                      69                  4315      0  
1                     234                      62                  3555      0  
2                     233                      76                  4450      0  
3                     201                      75                  4045      0  
4                     190                      60                  4145      0  

[5 rows x 23 columns]

In [6]:
z = dataset.iloc[:, 18].values
X = dataset.iloc[:, [1,18,4,5,6]].values
y = dataset.iloc[:, 22].values
print(X)

[[181.8  57.1  78.4  97.3  79.2]
 [170.7  56.3  70.2  88.2  81.1]
 [183.   58.9  76.8  95.8  80. ]
 [184.2  57.   82.4  99.6  78.3]
 [184.7  63.1  78.7  97.   91.8]
 [186.5  62.4  81.   99.5  79.5]
 [187.   60.7  79.3  97.3  81.5]
 [194.   78.1  85.  102.5  86.2]
 [168.1  50.9  69.5  90.4  75.3]
 [183.   61.2  78.2  94.8  77.2]
 [172.4  56.2  74.2  93.   75.5]
 [174.   54.3  76.4  88.8  77.8]
 [174.5  61.2  73.4  90.5  82.8]
 [170.5  61.   75.8  87.6  70. ]
 [183.   63.2  81.2  96.9  79.4]
 [175.5  60.9  72.6  93.3  80. ]
 [175.9  54.5  77.   89.7  77.6]
 [182.5  69.2  78.6  91.5  84. ]
 [175.   64.6  73.6  92.6  85.8]
 [171.1  58.6  76.5  88.7  81.3]
 [189.6  77.2  80.1  97.3  85. ]
 [184.3  63.7  81.3  95.6  79.4]
 [177.9  57.6  76.   91.6  76. ]
 [182.2  73.5  77.1  93.5  86.8]
 [176.   65.1  75.3  92.5  86.2]
 [173.6  63.6  77.1  88.6  82.5]
 [189.7  76.5  80.1  99.8  83.3]
 [184.6  66.3  78.4  94.8  81.9]
 [185.9  84.4  79.1  97.4  91.3]
 [172.   67.8  74.1  88.2  89.5]
 [179.   6

In [98]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 15)

## Data scaling

In [99]:
#from sklearn.preprocessing import StandardScaler
#scaler = StandardScaler()
#scaler.fit(X_train)
#X_train = scaler.transform(X_train)
#X_test = scaler.transform(X_test)

In [100]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 7)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

# We start the prediction

### K-Means cluster (Under-development)

In [119]:
# fitting KMeans    
kmeans = KMeans(n_clusters=3)
kmeans.fit(dataset)
example = [169.3,  59.2,  72.4,  86.7,  81. ]
exampleNP = np.array(example)
check = np.reshape(exampleNP, (-1,5))
print(check)

[[169.3  59.2  72.4  86.7  81. ]]


### Decision Tree Classifier

In [120]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
dtree_model = DecisionTreeClassifier(max_depth = 2).fit(X_train, y_train)
dtree_predictions = dtree_model.predict(X_test)
accuracy = dtree_model.score(X_test, y_test)
print(accuracy)
# creating a confusion matrix
cm = confusion_matrix(y_test, dtree_predictions)

0.6071428571428571


### SVM Classifier

In [126]:
from sklearn import datasets
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

# training a linear SVM classifier
from sklearn.svm import SVC
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train)
svm_predictions = svm_model_linear.predict(X_test) 
# model accuracy for X_test  
accuracy = svm_model_linear.score(X_test, y_test)
print(accuracy)
# creating a confusion matrix
cm = confusion_matrix(y_test, svm_predictions)
# save the model to disk
filename = 'SVM82Model.sav'
pickle.dump(LR_clf, open(filename, 'wb'))

0.8214285714285714


### KNN Classifier

In [106]:
# training a KNN classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train, y_train)
  
# accuracy on X_test
accuracy = knn.score(X_test, y_test)
print (accuracy)
  
# creating a confusion matrix
knn_predictions = knn.predict(X_test) 
cm = confusion_matrix(y_test, knn_predictions)


0.5357142857142857


### Logistic Regression

In [123]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
#  Train the model
LR_clf = LogisticRegression().fit(X_train, y_train)
#  Let's test it Talentmine model!!
LR_prediction = LR_clf.predict(X_test)
# Now compare between predicted sports and actual athletes
LR_accuracy = accuracy_score(y_test, LR_prediction)
# Accuracy | الضبط 
print(f'Logistic Regression Accuracy: {LR_accuracy:.2f} %')


Logistic Regression Accuracy: 0.50 %


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### Naive Bayes

In [124]:

# training a Naive Bayes classifier
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB().fit(X_train, y_train)
gnb_predictions = gnb.predict(X_test)
  
# accuracy on X_test
accuracy = gnb.score(X_test, y_test)
print (accuracy)
  
# creating a confusion matrix
cm = confusion_matrix(y_test, gnb_predictions)

0.5357142857142857


In [131]:
# load the model from disk
filename = 'SVM82Model.sav'
loaded_model = pickle.load(open(filename, 'rb'))
loaded_model.predict(check)

array([4])